from typing import Any, Generic, TypeVar, overload

from .base import BuiltInType, TypeBase

T = TypeVar("T", bound=TypeBase)
K = TypeVar("K", bound=TypeBase)
V = TypeVar("V", bound=TypeBase)

class CollectionBase(BuiltInType): ...

class _ArrayMeta(type):
    @overload
    def __call__(cls, elem_type: T, size: int, **kwargs: Any) -> Array[T]: ...
    @overload
    def __call__(cls, elem_type: T, size: tuple[int], **kwargs: Any) -> Array[T]: ...
    @overload
    def __call__(cls, elem_type: T, size: tuple[int, int], **kwargs: Any) -> Array[Array[T]]: ...
    @overload
    def __call__(cls, elem_type: T, size: tuple[int, int, int], **kwargs: Any) -> Array[Array[Array[T]]]: ...
    @overload
    def __call__(cls, elem_type: T, size: tuple[int, int, int, int], **kwargs: Any) -> Array[Array[Array[Array[T]]]]: ...
    @overload
    def __call__(cls, elem_type: T, size: tuple[int, ...], **kwargs: Any) -> Array[Any]: ...

class Array(CollectionBase, Generic[T], metaclass=_ArrayMeta):
    @overload
    def __init__(self: Array[T], elem_type: T, size: int, **kwargs: Any) -> None: ...
    @overload
    def __init__(self: Array[T], elem_type: T, size: tuple[int], **kwargs: Any) -> None: ...
    @overload
    def __init__(self: Array[Array[T]], elem_type: T, size: tuple[int, int], **kwargs: Any) -> None: ...
    @overload
    def __init__(self: Array[Array[Array[T]]], elem_type: T, size: tuple[int, int, int], **kwargs: Any) -> None: ...
    @overload
    def __init__(self: Array[Array[Array[Array[T]]]], elem_type: T, size: tuple[int, int, int, int], **kwargs: Any) -> None: ...
    @overload
    def __init__(self: Array[Any], elem_type: T, size: tuple[int, ...], **kwargs: Any) -> None: ...
    def __getitem__(self, index: int) -> T: ...
    def __len__(self) -> int: ...

class DynArray(CollectionBase, Generic[T]):
    def __init__(self, elem_type: T, *, max_length: int = ..., **kwargs: Any) -> None: ...
    def __getitem__(self, index: int) -> T: ...

class Queue(CollectionBase, Generic[T]):
    def __init__(self, elem_type: T, *, max_length: int = ..., **kwargs: Any) -> None: ...
    def __getitem__(self, index: int) -> T: ...

class AssocArray(CollectionBase, Generic[K, V]):
    def __init__(self, key_type: K, val_type: V, *, max_length: int = ..., **kwargs: Any) -> None: ...
