from typing import Any, Generic, Never, TypeVar, overload

from .typespec import TypeSpec

from .base import BuiltInType, TypeBase

T = TypeVar("T", bound=TypeBase)
K = TypeVar("K", bound=TypeBase)
V = TypeVar("V", bound=TypeBase)

class CollectionBase(BuiltInType): ...

class _ArrayMeta(type):
    @overload
    def __call__(cls, elem_type: T, size: int, **kwargs: Any) -> Array[T]: ...
    @overload
    def __call__(cls, elem_type: T, size: tuple[int], **kwargs: Any) -> Array[T]: ...
    @overload
    def __call__(cls, elem_type: T, size: tuple[int, int], **kwargs: Any) -> Array[Array[T]]: ...
    @overload
    def __call__(cls, elem_type: T, size: tuple[int, int, int], **kwargs: Any) -> Array[Array[Array[T]]]: ...
    @overload
    def __call__(cls, elem_type: T, size: tuple[int, int, int, int], **kwargs: Any) -> Array[Array[Array[Array[T]]]]: ...
    @overload
    def __call__(cls, elem_type: T, size: tuple[int, ...], **kwargs: Any) -> Array[Any]: ...

class Array(CollectionBase, Generic[T], metaclass=_ArrayMeta):
    @classmethod
    def __class_getitem__(cls, item: Any) -> TypeSpec: ...
    def __init__(self, *args: Never, **kwargs: Never) -> None: ...
    def __getitem__(self, index: int) -> T: ...
    def __len__(self) -> int: ...

class DynArray(CollectionBase, Generic[T]):
    @classmethod
    def __class_getitem__(cls, item: Any) -> TypeSpec: ...
    def __init__(self, *args: Never, **kwargs: Never) -> None: ...
    def __getitem__(self, index: int) -> T: ...

class Queue(CollectionBase, Generic[T]):
    @classmethod
    def __class_getitem__(cls, item: Any) -> TypeSpec: ...
    def __init__(self, *args: Never, **kwargs: Never) -> None: ...
    def __getitem__(self, index: int) -> T: ...

class AssocArray(CollectionBase, Generic[K, V]):
    @classmethod
    def __class_getitem__(cls, item: Any) -> TypeSpec: ...
    def __init__(self, *args: Never, **kwargs: Never) -> None: ...
